name: GArena
version: 1.0
api-version: 1.19
author: [Aang]
main: fr.greg.main.Main
depend: [Multiverse-Core]
commands:
  duel:
    description: Ouvre le menu arena
permissions:
  garena.use:
    description: Autorise tout
    default: op